### ISSUE TITLE
Add a license to this repository

### ISSUE THREAD

**Issue by lgp171188** [itiblog/pypaytabs#2]
This repository doesn't have a license and that means that the code is not open source and cannot be redistributed. See https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license.

So if that is not the intention here, can you please add a license to this repository?

Thanks!

**Comment by lgp171188** [comment]
@BelalSalahH, can you check this out? Thanks!

**Comment by BelalSalahH** [comment]
@lgp171188 done, Thanks for your hint
